### ISSUE TITLE
0 is passed as <nil> instead of 0 as int

### ISSUE THREAD

**Issue by recser** [francescogabbrielli/angular2-xmlrpc#1]
Hi, could you help me understand if this is an issue or i am doing something wrong ? parameter passed with callMethod as : 
['led', 0, 1] and the resulting xml is : <param><value><array><data><value><string>led</string></value><value><nil/></value><value><int>1</int></value></data></array></value></param>

**Comment by francescogabbrielli** [comment]
Hi recser you absolutely right. check last commit: do you think it will be enough to fix that?

**Comment by recser** [comment]
hi,
should be enough, would added input !== undefined to be sure there but should be fine as it is.

thanks, will wait on a new release to download and test it asap.

best regards

**Comment by francescogabbrielli** [comment]
Just released 👍

**Comment by recser** [comment]
hi, just tested. works as expected,
Thank you :thumbsup:
