### ISSUE TITLE
Array responses are broken (at least array of structs)

### ISSUE THREAD

**Issue by ifm-slang** [francescogabbrielli/angular2-xmlrpc#2]
It would be super easy to fix ... the sub `convert` is only missing the `this`

so, changing this:
https://github.com/francescogabbrielli/angular2-xmlrpc/blob/6c7ce0f463d496892eca20f6dbfb2d1627722d48/src/lib/xml2js.ts#L84

to `return valueNodes.map(this.convert, this);` would fix the issue

**Comment by francescogabbrielli** [comment]
Great catch! open pull request!

**Comment by ifm-slang** [comment]
🤔 I think this also means `  parseResponse(response:string):Object|null|undefined {` and `convert(input:Node):Object|null {` should also list `any[]` as return type

... I tried my fix only on the generated JavaScript, so the typing didn't matter ^^

**Comment by ifm-slang** [comment]
well, that was a bit more of a learning experience than expected 🤣 ( I am used to git, but never pushed to github )

btw. @francescogabbrielli it took me a while to find the "devDependencies" needed to build the current code ... was there a reason why they are not in the committed `package.json`?

**Comment by francescogabbrielli** [comment]
Sorry, I don't actually remember, it was a very quick porting. I think i had an ng-workspace project of which this was a module. I'll try to add some build instructions, but you are welcome to set it up in a different way
